export const APP_STATUS = {
  NEW_USER: 'NEW_USER',
  ONBOARDING: 'ONBOARDING',
  REGISTERED: 'REGISTERED',
  AUTHENTICATED: 'AUTHENTICATED',
};

export const NAVIGATORS = {
  CAROUSEL: 'CAROUSEL',
  ONBOARDING: 'ONBOARDING',
  MAIN: 'MAIN',
};
